# Examining Racial Discrimination in the US Job Market

### Background
Racial discrimination continues to be pervasive in cultures throughout the world. Researchers examined the level of racial discrimination in the United States labor market by randomly assigning identical résumés to black-sounding or white-sounding names and observing the impact on requests for interviews from employers.

### Data
In the dataset provided, each row represents a resume. The 'race' column has two values, 'b' and 'w', indicating black-sounding and white-sounding. The column 'call' has two values, 1 and 0, indicating whether the resume received a call from employers or not.

Note that the 'b' and 'w' values in race are assigned randomly to the resumes when presented to the employer.

### Exercises
You will perform a statistical analysis to establish whether race has a significant impact on the rate of callbacks for resumes.

Answer the following questions **in this notebook below and submit to your Github account**. 

   1. What test is appropriate for this problem? Does CLT apply?
   2. What are the null and alternate hypotheses?
   3. Compute margin of error, confidence interval, and p-value.
   4. Write a story describing the statistical significance in the context or the original problem.
   5. Does your analysis mean that race/name is the most important factor in callback success? Why or why not? If not, how would you amend your analysis?

You can include written notes in notebook cells using Markdown: 
   - In the control panel at the top, choose Cell > Cell Type > Markdown
   - Markdown syntax: http://nestacms.com/docs/creating-content/markdown-cheat-sheet


#### Resources
+ Experiment information and data source: http://www.povertyactionlab.org/evaluation/discrimination-job-market-united-states
+ Scipy statistical methods: http://docs.scipy.org/doc/scipy/reference/stats.html 
+ Markdown syntax: http://nestacms.com/docs/creating-content/markdown-cheat-sheet
****

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

# Show all plots:
%matplotlib inline

In [3]:
data = pd.io.stata.read_stata('D:/SpringBoard/EDAProjects/1508961196_racial_disc/racial_disc/data/us_job_market_discrimination.dta')

In [4]:
# number of callbacks for black-sounding names
sum(data[data.race=='b'].call)

157.0

In [5]:
data.head()

,id,ad,education,ofjobs,yearsexp,honors,volunteer,military,empholes,occupspecific,...,compreq,orgreq,manuf,transcom,bankreal,trade,busservice,othservice,missind,ownership
0,b,1,4,2,6,0,0,0,1,17,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
1,b,1,3,3,6,0,1,1,0,316,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
2,b,1,4,1,6,0,0,0,0,19,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,b,1,3,4,6,0,1,0,1,313,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,b,1,3,3,22,0,0,0,0,313,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4870 entries, 0 to 4869
Data columns (total 65 columns):
id                    4870 non-null object
ad                    4870 non-null object
education             4870 non-null int8
ofjobs                4870 non-null int8
yearsexp              4870 non-null int8
honors                4870 non-null int8
volunteer             4870 non-null int8
military              4870 non-null int8
empholes              4870 non-null int8
occupspecific         4870 non-null int16
occupbroad            4870 non-null int8
workinschool          4870 non-null int8
email                 4870 non-null int8
computerskills        4870 non-null int8
specialskills         4870 non-null int8
firstname             4870 non-null object
sex                   4870 non-null object
race                  4870 non-null object
h                     4870 non-null float32
l                     4870 non-null float32
call                  4870 non-null float32
city                  4870 non-null object
kind                  4870 non-null object
adid                  4870 non-null float32
fracblack             4784 non-null float32
fracwhite             4784 non-null float32
lmedhhinc             4784 non-null float32
fracdropout           4784 non-null float32
fraccolp              4784 non-null float32
linc                  4784 non-null float32
col                   4870 non-null float32
expminreq             4870 non-null object
schoolreq             4870 non-null object
eoe                   4870 non-null float32
parent_sales          1672 non-null float32
parent_emp            1722 non-null float32
branch_sales          608 non-null float32
branch_emp            658 non-null float32
fed                   3102 non-null float32
fracblack_empzip      1918 non-null float32
fracwhite_empzip      1918 non-null float32
lmedhhinc_empzip      1908 non-null float32
fracdropout_empzip    1918 non-null float32
fraccolp_empzip       1918 non-null float32
linc_empzip           1918 non-null float32
manager               4870 non-null float32
supervisor            4870 non-null float32
secretary             4870 non-null float32
offsupport            4870 non-null float32
salesrep              4870 non-null float32
retailsales           4870 non-null float32
req                   4870 non-null float32
expreq                4870 non-null float32
comreq                4870 non-null float32
educreq               4870 non-null float32
compreq               4870 non-null float32
orgreq                4870 non-null float32
manuf                 4870 non-null float32
transcom              4870 non-null float32
bankreal              4870 non-null float32
trade                 4870 non-null float32
busservice            4870 non-null float32
othservice            4870 non-null float32
missind               4870 non-null float32
ownership             4870 non-null object
dtypes: float32(42), int16(1), int8(12), object(10)
memory usage: 1.3+ MB

In [7]:
# Set options to inspect ALL of the columns:# Set o 
pd.options.display.max_columns = 65

# Inspect the structure of the dataframe:
data.head(10)

,id,ad,education,ofjobs,yearsexp,honors,volunteer,military,empholes,occupspecific,occupbroad,workinschool,email,computerskills,specialskills,firstname,sex,race,h,l,call,city,kind,adid,fracblack,fracwhite,lmedhhinc,fracdropout,fraccolp,linc,col,expminreq,schoolreq,eoe,parent_sales,parent_emp,branch_sales,branch_emp,fed,fracblack_empzip,fracwhite_empzip,lmedhhinc_empzip,fracdropout_empzip,fraccolp_empzip,linc_empzip,manager,supervisor,secretary,offsupport,salesrep,retailsales,req,expreq,comreq,educreq,compreq,orgreq,manuf,transcom,bankreal,trade,busservice,othservice,missind,ownership
0,b,1,4,2,6,0,0,0,1,17,1,0,0,1,0,Allison,f,w,0.0,1.0,0.0,c,a,384.0,0.989360,0.005500,9.527484,0.274151,0.037662,8.706325,1.0,5,,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
1,b,1,3,3,6,0,1,1,0,316,6,1,1,1,0,Kristen,f,w,1.0,0.0,0.0,c,a,384.0,0.080736,0.888374,10.408828,0.233687,0.087285,9.532859,0.0,5,,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
2,b,1,4,1,6,0,0,0,0,19,1,1,0,1,0,Lakisha,f,b,0.0,1.0,0.0,c,a,384.0,0.104301,0.837370,10.466754,0.101335,0.591695,10.540329,1.0,5,,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,b,1,3,4,6,0,1,0,1,313,5,0,1,1,1,Latonya,f,b,1.0,0.0,0.0,c,a,384.0,0.336165,0.637370,10.431908,0.108848,0.406576,10.412141,0.0,5,,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,b,1,3,3,22,0,0,0,0,313,5,1,1,1,0,Carrie,f,w,1.0,0.0,0.0,c,a,385.0,0.397595,0.180196,9.876219,0.312873,0.030847,8.728264,0.0,some,,1.0,9.4,143.0,9.4,143.0,0.0,0.204764,0.727046,10.619399,0.070493,0.369903,10.007352,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
5,b,1,4,2,6,1,0,0,0,266,4,0,0,0,1,Jay,m,w,0.0,1.0,0.0,c,s,386.0,0.336165,0.637370,10.431908,0.108848,0.406576,10.412141,1.0,,,1.0,40.0,135.0,40.0,135.0,0.0,0.008141,0.973413,11.137956,0.047958,0.413306,10.393723,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
6,b,1,4,2,5,0,1,0,0,13,1,1,1,1,1,Jill,f,w,1.0,0.0,0.0,c,s,386.0,0.002796,0.952140,10.453601,0.236445,0.124980,9.621058,1.0,,,1.0,40.0,135.0,40.0,135.0,0.0,0.008141,0.973413,11.137956,0.047958,0.413306,10.393723,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
7,b,1,3,4,21,0,1,0,1,313,5,0,1,1,1,Kenya,f,b,1.0,0.0,0.0,c,a,385.0,0.116624,0.728339,10.287047,0.139843,0.365636,9.933725,0.0,some,,1.0,9.4,143.0,9.4,143.0,0.0,0.204764,0.727046,10.619399,0.070493,0.369903,10.007352,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit
8,b,1,4,3,3,0,0,0,0,316,6,0,0,1,1,Latonya,f,b,0.0,1.0,0.0,c,s,386.0,0.080736,0.888374,10.408828,0.233687,0.087285,9.532859,1.0,,,1.0,40.0,135.0,40.0,135.0,0.0,0.008141,0.973413,11.137956,0.047958,0.413306,10.393723,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private
9,b,1,4,2,6,0,1,0,0,263,4,1,1,0,1,Tyrone,m,b,1.0,0.0,0.0,c,s,386.0,0.992043,0.004814,8.841738,0.295093,0.053182,8.507345,1.0,,,1.0,40.0,135.0,40.0,135.0,0.0,0.008141,0.973413,11.137956,0.047958,0.413306,10.393723,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Private

In [8]:
# Get a NULL count for the call column:
print("NULL observations for 'call' column:", data.call.isnull().sum())

# Get a NULL count for the race column:
print("NULL observations for 'race' column:", data.race.isnull().sum())

NULL observations for 'call' column: 0
NULL observations for 'race' column: 0

In [9]:
# Check for duplicate observations:
print('Number of duplicate records:', data.duplicated().sum())

Number of duplicate records: 0

###### No Duplicates and no NULL for race and calls. The data is decent

#####  Central Limit Theorem (CLT) 
This states that regardless of the population, the distribution of sample averages 
tends to be normal. This is a large enough size for this to hold true

###### NULL and Alternate Hypothesis
The hypothesis that we are testing is called the NULL hypothesis - i.e. Racial Discrimination does not exist in hiring practices in the United States when only 2 races are concerned, black and white. This means that the resume received a call from the Employer regardless of whether the name was black sounding or white sounding.

The Alternate hypothesis is that there is racial discrimination in the United States. This means that the resume received a call from the Employer if the name was white sounding and did not receive a call if it was black sounding. The proportion is significant in a random sample.

In [10]:
# Save callbacks filtered by race:
black_callbacks = data.call[data.race == 'b']
white_callbacks = data.call[data.race == 'w']

In [11]:
# Set up variables for statistics related to Black-Sounding names - 

# Sample Size:
n_black = len(data[data.race == 'b'])

# Number of callbacks for black-sounding names:
n_black_calls = black_callbacks.sum()

print('Number of Black-Sounding Résumés:', n_black)
print('Callbacks for Black-Sounding Names:', n_black_calls)


print('\n') # Add a line space.


# Set up variables for statistics related to Whtie-Sounding names - 

# Sample Size:
n_white = len(data[data.race == 'w'])

# Number of callbacks for white-sounding names:
n_white_calls = white_callbacks.sum()

print('Number of White-Sounding Résumés:', n_white)
print('Callbacks for White-Sounding Names:', n_white_calls)

Number of Black-Sounding Résumés: 2435
Callbacks for Black-Sounding Names: 157.0


Number of White-Sounding Résumés: 2435
Callbacks for White-Sounding Names: 235.0

In [12]:
def two_proportion_standard_error(hits1, attempts1, hits2, attempts2):
    """Return the standard error of two proportions."""
    
    # Calculate proportions:
    proportion1 = hits1/attempts1
    proportion2 = hits2/attempts2
    
    # Calculate standard error:
    SE = np.sqrt(proportion1*(1 - proportion1)/attempts1  +  proportion2*(1 - proportion2)/attempts2)
    return SE

def two_proportion_confidence_interval(hits1, attempts1, hits2, attempts2, alpha=0.05):
    """Return the confidence interval for a two-proportion test."""
    
    # Calculate proportions:
    proportion1 = hits1/attempts1
    proportion2 = hits2/attempts2
    difference_of_proportions = proportion1 - proportion2
    
    # Calculate standard error:
    SE = two_proportion_standard_error(hits1, attempts1, hits2, attempts2)
    
    # Save the critical value at the specified confidence:
    z_critical = norm.ppf(1 - 0.5*alpha)
    
    # Calculate margin of error:
    moe = z_critical * SE
    
    # Calculate confidence intervals:
    confidence_lower = proportion2 - proportion1 - moe
    confidence_higher = proportion2 - proportion1 + moe
    
    return difference_of_proportions, moe, confidence_lower, confidence_higher

In [13]:
# Compute and save confidence interval and margin of error:
difference_of_proportions, moe, confidence_lower, confidence_higher = two_proportion_confidence_interval(n_white_calls, n_white, n_black_calls, n_black)

print('Difference of Proportions: {0:0.4f}'.format(difference_of_proportions))
print('Margin of Error: {0:0.4f}'.format(moe))
print('95% Confidence Interval: [ {0:0.4f}  {1:0.4f} ]'.format(confidence_lower, confidence_higher))

Difference of Proportions: 0.0320
Margin of Error: 0.0153
95% Confidence Interval: [ -0.0473  -0.0168 ]

In [14]:
def two_proportion_z_test(hits1, attempts1, hits2, attempts2, one_tailed=False):
    """Return z-statistic and p-value."""
    
    # Calculate proportions:
    proportion1 = hits1/attempts1
    proportion2 = hits2/attempts2
    proportion = (hits1 + hits2)/(attempts1 + attempts2)
    
    # Calculate standard error:
    SE = np.sqrt(proportion * (1-proportion) * (1/attempts1 + 1/attempts2))
    
    # Calculate and return z-statistic and p-value:
    z = (proportion1 - proportion2)/SE
    p = 1 - stats.norm.cdf(abs(z))
    
    # If one_tailed = False(0), then p *= 2 is calculated:
    p *= 2 - one_tailed
    
    return z, p

In [15]:

# Compute and save z-statistic and p-value 
z, p = two_proportion_z_test(n_white_calls, n_white, n_black_calls, n_black)

print('z-statistic: {0:0.4f}'.format(z))
print('p-value: {0:0.4f}'.format(p))

z-statistic: 4.1084
p-value: 0.0000

 #### Statistical significance
The p-value is less than 0.05, and the confidence interval does not contain zero, so the null hypothesis is rejected.

##### Analysis 

This means that Race is one feature in receiving interview callbacks. 
Other factors have not been tested in a similar fashion. Gender could be a factor.